package com.icss.oa.notice.pojo;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTICE.NOTICE_ID
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTICE.TIME
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTICE.EMP_ID
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTICE.IS_TOP
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    private Integer isTop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTICE.NOTICE_TITLE
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    private String noticeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NOTICE.CONTENT
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTICE.NOTICE_ID
     *
     * @return the value of NOTICE.NOTICE_ID
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTICE.NOTICE_ID
     *
     * @param noticeId the value for NOTICE.NOTICE_ID
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTICE.TIME
     *
     * @return the value of NOTICE.TIME
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTICE.TIME
     *
     * @param time the value for NOTICE.TIME
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTICE.EMP_ID
     *
     * @return the value of NOTICE.EMP_ID
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTICE.EMP_ID
     *
     * @param empId the value for NOTICE.EMP_ID
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTICE.IS_TOP
     *
     * @return the value of NOTICE.IS_TOP
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public Integer getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTICE.IS_TOP
     *
     * @param isTop the value for NOTICE.IS_TOP
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public void setIsTop(Integer isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTICE.NOTICE_TITLE
     *
     * @return the value of NOTICE.NOTICE_TITLE
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public String getNoticeTitle() {
        return noticeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTICE.NOTICE_TITLE
     *
     * @param noticeTitle the value for NOTICE.NOTICE_TITLE
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public void setNoticeTitle(String noticeTitle) {
        this.noticeTitle = noticeTitle == null ? null : noticeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NOTICE.CONTENT
     *
     * @return the value of NOTICE.CONTENT
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NOTICE.CONTENT
     *
     * @param content the value for NOTICE.CONTENT
     *
     * @mbggenerated Mon Jul 20 08:46:51 CST 2015
     */
    
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    
    
	public Notice() {
		super();
	}

	public Notice(Date time, Integer empId, Integer isTop, String noticeTitle,
			String content) {
		super();
		this.time = time;
		this.empId = empId;
		this.isTop = isTop;
		this.noticeTitle = noticeTitle;
		this.content = content;
	}

	public Notice(Integer noticeId, Date time, Integer empId, Integer isTop,
			String noticeTitle, String content) {
		super();
		this.noticeId = noticeId;
		this.time = time;
		this.empId = empId;
		this.isTop = isTop;
		this.noticeTitle = noticeTitle;
		this.content = content;
	}

	@Override
	public String toString() {
		return "Notice [noticeId=" + noticeId + ", time=" + time + ", empId="
				+ empId + ", isTop=" + isTop + ", noticeTitle=" + noticeTitle
				+ ", content=" + content + "]";
	}
    
}